
about :

  name : wBaseNodeJsCpp
  description : Collection of base tools for writing native NodeJs modules.
  version : 0.1.0

path :

  in : '.'
  cpp : './cpp'
  out : 'out'
  repository : git+https:///github.com/Wandalen/wBaseNodeJsCpp.git
  bugs : https:///github.com/Wandalen/wBaseNodeJsCpp/issues

step  :

  export.out.debug :
    inherit : module.export
    export : path::cpp
    tar : 0
    criterion :
      debug : 1

build :

  debug.raw.export :
    criterion :
      default : 1
      debug : 1
      export : 1
    steps :
      - step::export.out.debug
